name: ocr_project
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_tesseract_ocr: ^0.4.0
  toast: ^0.3.0
  flutter_speed_dial: ^6.0.0
  dio: ^4.0.6
  html: ^0.15.0
  shared_preferences: ^2.0.15
  modal_progress_hud_nsn: ^0.3.0
  flukit: ^3.0.1
  image_picker: ^0.8.5+3
#  flutter_mobile_vision_2: ^0.1.15
#  camera: ^0.10.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/tessdata_config.json
   - assets/tessdata/eng.traineddata
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #